### PR TITLE
Separating concerns - a discussion pull request

### PR DESCRIPTION
**Pull request by bubbafat**
This pull request could be committed but is more meant to be a discussion point.

I found it difficult to grok the code when the local and proxy thing code was intermixed and when the registry was used all over.  What I did was:

1. Create a Registry type.  This has functions for registering (actually creating) things and proxies as well as finding them.  It also handles dependency resolution and firing start events.

2. Create a LocalThing and ProxyThing class - these are created by the registry (since everything must be registered, creating via the registry ensures that nothing is ever left out.

3. Some refactoring to support these changes.

It also changes how things are registered.  Local things are registered only by their path.  E.g., "http://localhost:8888/wot/switch12" is registered as "/wot/switch12" but proxied things are registered by their entire URI.  E.g., "http://remote.server/wot/switch12" is the uri and the id.  They are stored in separate collections as well (though they could be stored together - this was just to keep the search space limited to the type we know we care about).

I personally find this code a bit easier to approach because it is clearer to me what each part is responsible for and the side-effects of changes are easier to understand.  As more people get interested in the code base it might encourage contributions if the mental cost of understand the code wasn't as high.

It also adds some tests around the registry.

One thing this code me thinking about was how to handle proxies to local objects in various combinations.  For example:

```JavaScript
// fake syntax for brevity

// this should return a real object from wot.proxy since it exists locally
wot.thing("/wot/switch12");
wot.proxy("http://localhost/wot/switch12");
```

But what if we request the proxy first?

```JavaScript
// this should return a proxy first and then a real object - no way to avoid that
// but could the proxy somehow promote to a real object?  Maybe a "fake" proxy
// that simply create continuations - and then when it becomes realized locally it 
// simply re-writes the various properties/actions/events to be local
wot.proxy("http://localhost/wot/switch12");  // gets a proxied thing
wot.thing("/wot/switch12");
wot.proxy("http://localhost/wot/switch12"); // gets a real thing
```

### CODE REVIEW

**Comment by draggett** [comment]
Thanks for working on this.  I will need some time to review the changes as I am travelling today and will be very jet lagged tomorrow.  I like the idea of refactoring to make the code easier to understand, but want to ensure that it still behaves correctly.

In respect to proxies for local things, is this needed given that you could just return the thing?
```
// fake syntax for brevity

// this should return a real object from wot.proxy since it exists locally
wot.thing("/wot/switch12");
wot.proxy("http://localhost/wot/switch12");
```
I am not sure what these are supposed to do.  Currently we have:
```
wot.thing(name, model, implementation)
```
which registers the thing under its name and model, and binds it to its implementation based upon the model, and calls the implementation start method once the dependencies of this thing on other things have been resolved to either local things or to proxies for remote things.  The current code allows you to register a thing before the things it depends on. This is implemented using a means to track what things depend on other things, so that when those things are registered, the dependencies can be resolved.  

Due to the possibility of circular dependencies between things, you can't guarantee that when a thing's implementation start method is called, that the corresponding start methods have been called for all of the things it depends upon. To address this, the code queues invocation of actions and updates of properties until after the thing's start method has been executed.
```
wot.register_proxy(uri for model, handler for thing)
```
where the hander is called with the thing object as a proxy for the thing identified by the URI. This is asynchronous as you first need to download the model.

Given the relative complexity of all this, I hope you don't mind me taking some time to look at your proposed changes in some detail.

**Comment by bubbafat** [comment]
Nothing here is time-critical.  Enjoy your weekend - if you get to this sometime next week, cool.  If not, no worries.

> In respect to proxies for local things, is this needed given that you could just return the thing?

If the thing exists - yes, return the thing.  If the thing does not yet exist, but is deterministically local, we have lots of options - I'm not sure what the best one is.

> I am not sure what these are supposed to do.

It was just brevity in my note, not a change in syntax.  The (name,model,implementation) arguments are still used - nothing changed there.  Demo.js should be unchanged.

> The current code allows you to register a thing before the things it depends on

This change does as well - using the same mechanism (well, basically - yours was a bit more efficient because it was an associative array of arrays, where as mine is a flat array - but it is hidden in the registry so that could change without API impact).  There is a test for that case added as well.  

I have a lot of questions around how creating a proxy before the think it depends on exists, but I think how to handle dependent "real" things is pretty straight-forward.

> To address this, the code queues invocation of actions and updates of properties until after the thing's start method has been executed.

Yup, I don't think I changed this.  Just moved the code to the registry since that's where resolution happens.

That said - I do think that the idea of queuing changes should probably be discussed in more detail.  I'm wondering if there are scenarios where deferring execution might end up being a problem (e.g., the calls appear synchronous but are in fact not - would this be confusing or problematic).  

Or perhaps a scenario where ProxyFoo (a proxy to Foo) is created before Foo.start() is executed - should ProxyFoo.functionCall(); result in a queued invocation as well?

> Given the relative complexity of all this, I hope you don't mind me taking some time to look at your proposed changes in some detail.

No worries.  I don't even mind if we throw the whole thing out - I just find it easier to have some conversations, especially around refactorings, if I actually work through the code and think about it.

My primary goal is to reduce perceived complexity by separating concerns.  If this isn't the right way, then I'm glad we got the conversation started so we can find the right one.

**Comment by draggett** [comment]
Catching up with email while waiting to board my flight to London ...

> If the thing exists - yes, return the thing. If the thing does not yet exist, but is deterministically local, we have lots of options - I'm not sure what the best one is.

That would result in complicating scripting by having to handle both cases separately.  In the current code, if the proxied thing is already registered then the handler is called immediately, otherwise it is called when available. The script writer has only one path to deal with not two.

> That said - I do think that the idea of queuing changes should probably be discussed in more detail. I'm wondering if there are scenarios where deferring execution might end up being a problem (e.g., the calls appear synchronous but are in fact not - would this be confusing or problematic).

It is should always be regarded as asynchronous. Updating a property or invoking an action may take time to take effect. On a proxy, this is due to the messaging needed to propagate the update/action to the thing the proxy depends upon.  On a local thing, the object may encapsulate drivers for IoT technologies like Bluetooth or ZigBee. Battery operated IoT devices may spend most of their time asleep, so that a lag is incurred whilst waiting for the next communication window to open with the device.

**Comment by bubbafat** [comment]
> if the proxied thing is already registered then the handler is called immediately, otherwise it is called when available

I agree that the API user should not have to think about whether an object is a "real" local thing or something else (even something that looks and feels like a real local thing).

It is very possible I'm misunderstanding the scenarios here.  I was concerned about a denial of service problem.  Basically this:

Say I have a "Smart Door" named /wot/door.  This door is comprised of a smart lock, a sensor that determines if the door is open or not and a camera that takes a picture of anyone who opens the door.  /wot/door depends on /wot/camera - so /wot/door start() function won't be called until /wot/camera is online.  But /wot/camera is broken - does that mean /wot/door would never come online?

My assumption is that /wot/door would never come online until the dependency was removed - so either we'd need to return a proxy that defers calls until the thing exists (which could be equally confusing) or provide a mode that allows loading a thing without having to have all the dependent things online (maybe none, only a subset, etc).

It is very possible I'm way off base here and this is not an issue.

> It is should always be regarded as asynchronous.

Agreed.  I have fond memories of sitting for 15+ minutes waiting for ZigBee blurts to make their way from my test harness to various devices.

I suppose it comes back to this type of start function:

```JavaScript

start: function(thing) {
    thing.function1();
    thing.function2();
    thing.function3();
}
```

Most node developers would see this and expect it to execute synchronously and to have each function complete in series.

They would be wrong.

The API could help by being more prescriptive; making it clear that neither of these are true.  It should go further, though, and make it possible to be true.

We could use callbacks like:

```JavaScript
start: function(thing) {
    thing.function1(function() {
        thing.function2(function() {
            thing.function3();
        }
    }
}
```

Or more succinctly using promises

```JavaScript
start: function(thing) {
    thing.function1()
         .then(function2)
         .then(function3);
}
```

Or other ways.

Ultimately the onus is on the developer to make sure they understand the framework, but right now they have no way to get this behavior without third-party libraries and only after understanding that they need to think async in an otherwise synchronous platform.

**Comment by draggett** [comment]
> Say I have a "Smart Door" named /wot/door. This door is comprised of a smart lock, a sensor that determines if the door is open or not and a camera that takes a picture of anyone who opens the door. /wot/door depends on /wot/camera - so /wot/door start() function won't be called until /wot/camera is online. But /wot/camera is broken - does that mean /wot/door would never come online?

Yes and no.  Let's assume that the door and camera are on separate devices. The door's start function will be called once the model for the camera has been retrieved so that its proxy can be instantiated.  A timeout error would occur if the model can't be retrieved from the camera. The current NodeJS code needs more work to handle errors better.

We also need to start discussing discovery mechanisms and abstraction layers.  In principle, the devices could be discovered in a variety of ways, so that the models may be accessed from say a hub server rather than the IoT device itself. We need some use cases to ground this discussion.

**Comment by bubbafat** [comment]
> A timeout error would occur if the model can't be retrieved from the camera.

Aha!  I am confusing the model with the actual device.  This is a great point - thank you.

> We also need to start discussing discovery mechanisms and abstraction layers.

I look forward to this.  The end-to-end is still fuzzy to me.

**Pull request closed without merging**
