### PR TITLE
Express, Bootstrap, logging, modular design,security

### PR DESCRIPTION
**Pull request by zsoltpardi**
In this commit the  Express web framework is wired up to support responsive layout design and mobile UI using Bootstrap and jquery. This allows using partial views, MVC paradigm, template based UI and will be easier to implement the integration of MVM libraries such as knockout.js. There will be lots of devices to visualize and I thought it is good idea to have in place a flexible, relatively easy to use, responsive, ideally Ajax oriented MVM library such as knockout and using Express in the back-in, as well as a template engine such as Handlebars (which is also added in this pull request)  that makes the UI design easier.

Added Winston to handle logging. Once we start to wire up the devices I thought it will be very useful to have a logging module and persistent logs. Winston encapsulates logging quite nicely and handles persistent logs relatively well.

I was thinking about how to go forward with regards to have a more robust server infrastructure and have a design in place that addresses high availability and scalability requirements. In most use cases WoT servers will be probably load balanced, and I thought the design should support such infrastructure and allow scalability as well. Just as a first step on that road the libs folder added to store the modules that should be common to various objects within the process. In first step the registry array (that stores the things) has been moved to the libs folder. The idea is not to pass it as a reference from one module to an other, but make it available in a decoupled manner. This also enable to make it persistent in the future. Load balanced WoT servers probably will have to store the lists and resources in a database to address high availability requirements and in order to do that I thought it is better to have an architecture in place in the first place that will support a more modular design and scalable implementation.

Please note, the logs folder must exists in the directory tree for the log files.

I also created the first draft of WoT security. The idea is to use PPKI to manage authentication, access control and ensure data integrity. 
I have the nodejs working code for all ECC functions, the JS client side port of that, as well as C and  C++ implementations. I am also testing it on Nucleus RTOS, so if WoT choose to accommodate the concept of the security.md document  then I will be able to have the implementation files in place relatively quickly. Also, if we WoT will go down on this route terms of security I will be able to elaborate the concept with UML component, object, sequence, etc. diagrams.

### CODE REVIEW

**Comment by drasko** [comment]
Great! +1 for Express.

Remarks:
- JWT is interesting from security aspect (http://jwt.io/)
- Please look at RiotOS (http://www.riot-os.org/) instead a closed source and commercial Nucleus RTOS
- Do we have to create `logs` dir manually or it should be commited to the structure:

```
drasko@Lenin:~/web-of-things-framework$ node httpd.js 
info: WoT Express server start
info: WoT Express server listening on port 8888
error: uncaughtException: ENOENT, open '/home/drasko/web-of-things-framework/logs/application.log' date=Mon Jul 27 2015 22:33:53 GMT+0200 (CEST), pid=809, uid=1000, gid=1000, cwd=/home/drasko/web-of-things-framework, execPath=/usr/local/bin/node, version=v0.12.0, argv=[node, /home/drasko/web-of-things-framework/httpd.js], rss=35233792, heapTotal=30578176, heapUsed=18611016, loadavg=[0.37646484375, 0.29541015625, 0.2880859375], uptime=358546, trace=[column=null, file=null, function=Error, line=null, method=null, native=true], stack=[Error: ENOENT, open '/home/drasko/web-of-things-framework/logs/application.log',     at Error (native)]
```

**Comment by zsoltpardi** [comment]
Thanks for pointing out jwt.io. That's fantastic, it supports ECDSA as well.

We should definitely use open source RTOS instead of the closed source Nucleus. 

I made a note in the above pull request document that please make sure the "logs" folder exists, and it's not quite good and yes it should be committed to the directory tree. My git client is not committing empty folders, but I will try to manage to include it with the next commit.

**Comment by drasko** [comment]
@zsoltpardi yes, jwt token-based security can be very useful for this framework. I can see that you looking more at decentralisation, so I guess it would be very interesting to see what IBM Adept ill bring (https://gigaom.com/2014/09/09/check-out-ibms-proposal-for-an-internet-of-things-architecture-using-bitcoins-block-chain-tech/) and also where the guys from Filament are heading (https://medium.com/@FilamentHQ/a-declaration-of-device-independence-b6f83e8b6441), so that we can leverage Bitcoin mechanisms. But still, I think they will be pretty demanding for small MCU-s that we are targeting.

Riot is pretty decent now, still in academic waters, but has a lot of IoT protocols already implemented. The only RTOS with similar stack that I can imagine is mbed OS (https://mbed.org/technology/os/, not to be confused with already existing mbed RTOS) - but we will have to see it's openness (I doubt that it will be completely open source).

**Comment by zsoltpardi** [comment]
@drasko absolutely, I have been building IoT solutions on the blockchain as well as using smart contracts and digital currencies for IoT micropayments. IBM's ADEPT is a great advocate of the blockchain technology, thought it takes the less desirable attributes of the BTC blockchain such as the lack of privacy and traceability of transactions. I try to solve that Bitcoin issues with a private/public blockchain concept in my solution, so the public can't trace let say who opens a door which privacy aspect of the operation is overlooked by ADEPT in my opinion. If decentralization is in-scope for WoT at all then I will be happy to commit our decentralized, blockchain based solution. It would be great if a decentralized, P2P IoT solution could be the part of W3C.

I think JWT and JSON Web Signature (JWS) could be very useful and we should follow the open standards in this case as well. Thanks for pointing it out, I should definitely try to use them with any security implementations.

What do you think about FreeRTOS? Isn't FreeRTOS the most widely used and more mature RTOS? I understand not all modules are open source, but if I understand it correctly the main peripherals libraries and ssl cryptography library which is my primary interest for security is open source. 

mbed OS looks awesome, it has crypto, Wi-fi,  Zigbee, etc. and implements CoAP, HTTP, MQTT protocols, and they claim it is open source "The mbed SDK is licensed under the permissive Apache 2.0 open source licence." at https://developer.mbed.org/handbook/mbed-SDK, but you could be right that it won't be finally open source.

**Comment by drasko** [comment]
@zsoltpardi I have been reading lately a lot about blockchain approach, and I am not expert on the subject. Actually, I am a bit surprised that these technologies are emerging now when we are trying to solve a problem of coin cell battery lasting 5 years on a BLE device. This is sleeping node, and with all the calculations it would have to do I think we can forget blockchain algorithms. It can be useful for a washing machine running Linux, but still I do not see where they are really heading when AllJoyn (https://allseenalliance.org/) and Iotivity (https://www.iotivity.org/) are already proposing (similar) soutions for proximal multi-technology inter-operational networks. That being said, I think that main purpose of WoT framework would be to standardize these approaches, but having in ming all the work being done on these projects it will take a miracle (or a hell good architecture :)).

FreeRTOS is a general purpose RTOS, and does not target IoT applications specifically. So it does not include many things in the stack. Besides, I always prefered UNIX-like RTOS-es, for example NuttX (http://www.nuttx.org/).

However, two really IoT oriented solutions are:
1. Contiki - http://www.contiki-os.org/
2. Riot - http://www.riot-os.org/

Riot is like Contiki, but more Linux-like. Both are totally open, Contiki MIT and Riot LGPL.

What is important for these RTOSes is that they pack support for 802.15.4 and 6LoWPAN, then RPL and CoAP. Also often DTLS for security. Or CBOR as JSON substitution. MQTT can be easily added through Eclipse Paho project, as a client app.

All these stuff can be probably added to FreeRTOS as well, but with a lot of effort. It is worth to do a comparison, but I would personaly lean towards these 3 RTOSes I mentioned (Contiki, Riot and Mbed OS - if it stays open when published).

**Comment by zsoltpardi** [comment]
The blockchain tech, as you said is not suitable for low power and battery powered use cases, and I agree it is mainly for more powerful IoT devices when the decentralization is a concern, P2P is a requirement or perhaps payments needs to be handled on device level and digital currency or payment token used for payment processing, but that definitely is not in-scope for WoT.

Thanks for pointing out the issues with FreeRTOS. I used  Contiki in the past, but I am not familiar with Riot, and it seems really good solutions with lots of board support. I will definitely start looking into it.

**Comment by drasko** [comment]
Speaking of UI, AngularJS would be better choice IMHO.

**Comment by zsoltpardi** [comment]
Both knockout and AngularJS are very popular libraries and I would imagine we will have both. Personally, I am more familiar with knockout and I prefer it over Angular, but I think AngularJS developers will be rolling out web portals soon that use AngularJS within the WoT tree.

**Pull request merged**
