### PR TITLE
Resolving urls properly to run locally.

### PR DESCRIPTION
**Pull request by apexskier**
Running locally, I wasn't able to access things properly. They were stored in the registry with the full url as a key (http://localhost:8888/wot/...) but were being accessed with the absolute url (/wot/...). Also resolves a web sockets bug and adds more debug info.

### CODE REVIEW

**Comment by apexskier** [comment]
I've added some changes to set up the web socket connection to actually proxy changes to things as well. Node now shares its local things registry with the wsd.

**Comment by draggett** [comment]
An open question for me is how to robustly distinguish local from remote URIs given the multiplicity of IP addresses possible: localhost, 127.0.0.1, and the external IP addresses on potentially multiple network interfaces, and the additional complications of IPv6. Any ideas?

**Comment by apexskier** [comment]
I don't have a really nice solution for this. Obviously, uris without hostnames can be assumed to be local or "managed" by the first hub they arrive at. One workable solution is to manually specify a list of hostnames, possibly by looking at `/etc/hosts`.

Because we don't have a single unique ID per node, we can't just test if a node exists locally, because the absolute path of two nodes could be identical (you and I both have a //host/wot/door1).

**Comment by draggett** [comment]
> On 4 Jun 2015, at 16:22, Cameron Little <notifications@github.com> wrote:
> 
> I don't have a really nice solution for this. Obviously, uris without hostnames can be assumed to be local or "managed" by the first hub they arrive at. One workable solution is to manually specify a list of hostnames, possibly by looking at /etc/hosts.
> 
> Because we don't have a single unique ID per node, we can't just test if a node exists locally, because the absolute path of two nodes could be identical (you and I both have a //host/wot/door1).
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/w3c/web-of-things-framework/pull/10#issuecomment-108933544>.
> 

I did some research and coded up a means to robustly distinguish URIs for local and remote things, but have yet to sync it to GitHub website.  I plan to work on this some more over the weekend as I am busy on other work right now.  The idea is to reuse proxies for the same thing. This should be very simple.  I also want to add the API for registering a proxy on another server via HTTP as a means to set up proxies on cloud servers.

Many thanks for your help.

—
   Dave Raggett <dsr@w3.org <mailto:dsr@w3.org>>

**Pull request merged**
